group=org.eclipse.edc
version=0.16.0-SNAPSHOT
edcScmUrl=https://github.com/eclipse-edc/Connector.git
edcScmConnection=scm:git:git@github.com:eclipse-edc/Connector.git
systemProp.http.proxyHost=tudas-proxy.rd.hu.t-internal.com
systemProp.http.proxyPort=3128
systemProp.https.proxyHost=tudas-proxy.rd.hu.t-internal.com
systemProp.https.proxyPort=3128